#
# Message in A bottle Docker Compose file
#

version: "3.6"

services:
  mib_notifications:
    <<: &mib_notifications
      # Building the image
      image: "mib-notifications:latest"
      build:
        context: .
        dockerfile: Dockerfile 
      env_file:
        - env_file
